# -*- coding: utf-8 -*-
"""Build the Exchange Microstructure confirmation and prediction-overlay report.

The report uses the public snapshot generated by ``exchange_market_data.py``.
It confirms or weakens technical signals (Wyckoff, Fibonacci, RSI, patterns,
breakouts) without changing the mathematical calculation of those indicators.

The module computes a candidate ±1 signal but keeps Global Confluence weight at
0 until the 7-day tracker has at least 30 matured controls, at least 55% directional
accuracy and positive direction-adjusted return. The 30-day prediction overlay
has an independent 30-control gate.
"""

from __future__ import annotations

import csv
import json
import math
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any


REPORTS_DIR = Path("reports")
LATEST_REPORT = REPORTS_DIR / "latest_report.md"
SNAPSHOT_PATH = REPORTS_DIR / "exchange_market_data_snapshot.json"
HEALTH_PATH = REPORTS_DIR / "exchange_market_data_health.json"
STORAGE_STATUS_PATH = REPORTS_DIR / "exchange_storage_status.json"
TECHNICAL_PATH = REPORTS_DIR / "technical_structure_metrics.csv"
SCANNER_PATH = REPORTS_DIR / "latest_scanner_summary.csv"
TRACKER_METRICS_PATH = REPORTS_DIR / "exchange_signal_tracker_metrics.csv"
INTRADAY_PATH = REPORTS_DIR / "exchange_market_data_intraday.csv"

REPORT_PATH = REPORTS_DIR / "exchange_microstructure_report.md"
DIAGNOSTICS_PATH = REPORTS_DIR / "exchange_source_diagnostics.md"
METRICS_PATH = REPORTS_DIR / "exchange_microstructure_metrics.csv"
HISTORY_PATH = REPORTS_DIR / "exchange_microstructure_history.csv"
PREDICTION_PATH = REPORTS_DIR / "exchange_prediction_overlay.csv"

START_MARKER = "<!-- EXCHANGE_MICROSTRUCTURE_START -->"
END_MARKER = "<!-- EXCHANGE_MICROSTRUCTURE_END -->"

ASSETS = ("BTC", "SOL", "DOGE")
LIQ_MIN_USD = {"BTC": 250_000.0, "SOL": 50_000.0, "DOGE": 20_000.0}
HISTORY_KEY = ("signal_date", "asset")


METRIC_FIELDS = [
    "generated_utc",
    "asset",
    "price",
    "data_coverage",
    "source_health",
    "exchange_count",
    "binance_available",
    "bybit_available",
    "kucoin_available",
    "binance_status",
    "bybit_status",
    "kucoin_status",
    "raw_score",
    "candidate_global_score",
    "global_score",
    "global_activation_status",
    "calibration_controls_7d",
    "calibration_accuracy_7d",
    "calibration_signed_return_7d",
    "bias",
    "confidence",
    "flow_score",
    "derivatives_score",
    "crowding_score",
    "liquidation_score",
    "technical_confirmation_score",
    "funding_rate_pct",
    "basis_pct",
    "price_change_24h_pct",
    "open_interest_usd_combined",
    "oi_change_4h_pct",
    "oi_change_24h_pct",
    "global_long_short_ratio",
    "top_account_long_short_ratio",
    "top_position_long_short_ratio",
    "taker_buy_sell_ratio_1h",
    "taker_buy_sell_ratio_4h",
    "taker_buy_sell_ratio_24h",
    "orderbook_imbalance_0_25pct",
    "orderbook_imbalance_0_5pct",
    "orderbook_imbalance_1_0pct",
    "spread_bps",
    "intraday_samples_4h",
    "intraday_samples_24h",
    "intraday_span_hours",
    "intraday_taker_ratio_avg_4h",
    "intraday_taker_ratio_avg_24h",
    "intraday_book_imbalance_avg_4h",
    "intraday_book_imbalance_avg_24h",
    "intraday_funding_avg_24h",
    "intraday_oi_change_4h_pct",
    "intraday_oi_change_24h_pct",
    "intraday_price_change_4h_pct",
    "intraday_price_change_24h_pct",
    "intraday_long_liquidation_usd_observed_24h",
    "intraday_short_liquidation_usd_observed_24h",
    "intraday_liquidation_events_observed_24h",
    "bullish_consensus_count",
    "bearish_consensus_count",
    "divergent_metric_count",
    "binance_funding_rate_pct",
    "bybit_funding_rate_pct",
    "kucoin_funding_rate_pct",
    "binance_open_interest_usd",
    "bybit_open_interest_usd",
    "kucoin_open_interest_usd",
    "binance_taker_ratio",
    "bybit_taker_ratio",
    "kucoin_taker_ratio",
    "binance_book_imbalance_0_5pct",
    "bybit_book_imbalance_0_5pct",
    "kucoin_book_imbalance_0_5pct",
    "long_liquidation_usd_sample",
    "short_liquidation_usd_sample",
    "liquidation_events_sample",
    "largest_liquidation_usd_sample",
    "wyckoff_confirmation",
    "fibonacci_confirmation",
    "rsi_confirmation",
    "pattern_confirmation",
    "breakout_quality",
    "liquidity_map",
    "detail",
]

PREDICTION_FIELDS = [
    "generated_utc",
    "asset",
    "raw_positive_rate_30d",
    "raw_return_p50_30d",
    "exchange_score",
    "tracker_controls_30d",
    "tracker_accuracy_30d",
    "overlay_status",
    "overlay_weight",
    "adjusted_positive_rate_30d",
    "adjusted_return_p50_30d",
    "note",
]

HISTORY_BASE_FIELDS = [
    "signal_date",
    "asset",
    "price",
    "raw_score",
    "candidate_global_score",
    "global_score",
    "global_activation_status",
    "bias",
    "confidence",
    "data_coverage",
    "exchange_count",
    "bullish_consensus_count",
    "bearish_consensus_count",
    "divergent_metric_count",
    "funding_rate_pct",
    "basis_pct",
    "price_change_24h_pct",
    "open_interest_usd_combined",
    "oi_change_4h_pct",
    "oi_change_24h_pct",
    "global_long_short_ratio",
    "top_position_long_short_ratio",
    "taker_buy_sell_ratio_4h",
    "taker_buy_sell_ratio_24h",
    "orderbook_imbalance_0_5pct",
    "orderbook_imbalance_1_0pct",
    "intraday_samples_24h",
    "intraday_span_hours",
    "intraday_taker_ratio_avg_4h",
    "intraday_taker_ratio_avg_24h",
    "intraday_book_imbalance_avg_4h",
    "intraday_book_imbalance_avg_24h",
    "intraday_funding_avg_24h",
    "intraday_oi_change_4h_pct",
    "intraday_oi_change_24h_pct",
    "intraday_price_change_4h_pct",
    "intraday_price_change_24h_pct",
    "intraday_long_liquidation_usd_observed_24h",
    "intraday_short_liquidation_usd_observed_24h",
    "intraday_liquidation_events_observed_24h",
    "long_liquidation_usd_sample",
    "short_liquidation_usd_sample",
    "liquidation_events_sample",
    "scanner_positive_rate_30d",
    "scanner_return_p50_30d",
    "overlay_status",
    "overlay_weight",
    "adjusted_positive_rate_30d",
    "adjusted_return_p50_30d",
    "created_utc",
]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def utc_now_text() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def utc_date() -> str:
    return datetime.now(timezone.utc).date().isoformat()


def safe_float(value: Any, default: float | None = None) -> float | None:
    try:
        number = float(value)
        return number if math.isfinite(number) else default
    except (TypeError, ValueError):
        return default


def safe_int(value: Any, default: int = 0) -> int:
    number = safe_float(value)
    return int(number) if number is not None else default


def safe_text(value: Any, default: str = "") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return text if text and text.lower() not in {"nan", "none", "null"} else default


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return payload if isinstance(payload, dict) else {}
    except Exception:
        return {}


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            return list(csv.DictReader(handle))
    except Exception:
        return []


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8", newline="\n")
    tmp.replace(path)


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})
    tmp.replace(path)


def normalize_asset(value: Any) -> str:
    return safe_text(value).upper().replace("-USD", "").replace("USDT", "")



def parse_utc_datetime(value: Any) -> datetime | None:
    text = safe_text(value).replace("Z", "+00:00")
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=timezone.utc)
        return parsed.astimezone(timezone.utc)
    except ValueError:
        return None


def average_values(rows: list[dict[str, Any]], key: str) -> float | None:
    values = [safe_float(row.get(key)) for row in rows]
    values = [value for value in values if value is not None]
    return sum(values) / len(values) if values else None


def sum_values(rows: list[dict[str, Any]], key: str) -> float:
    return sum(value for value in (safe_float(row.get(key)) for row in rows) if value is not None)


def period_change(rows: list[dict[str, Any]], key: str, minimum_span_hours: float) -> float | None:
    if len(rows) < 2:
        return None
    first = safe_float(rows[0].get(key))
    last = safe_float(rows[-1].get(key))
    first_time = parse_utc_datetime(rows[0].get("timestamp_utc"))
    last_time = parse_utc_datetime(rows[-1].get("timestamp_utc"))
    if first in (None, 0) or last is None or first_time is None or last_time is None:
        return None
    if (last_time - first_time).total_seconds() < minimum_span_hours * 3600:
        return None
    return (last / first - 1.0) * 100.0


def intraday_summaries() -> dict[str, dict[str, Any]]:
    rows = read_csv_rows(INTRADAY_PATH)
    parsed: list[dict[str, Any]] = []
    for row in rows:
        timestamp = parse_utc_datetime(row.get("timestamp_utc"))
        asset = normalize_asset(row.get("asset"))
        if timestamp is None or asset not in ASSETS:
            continue
        item = dict(row)
        item["_timestamp"] = timestamp
        item["asset"] = asset
        parsed.append(item)
    if not parsed:
        return {}

    latest_time = max(row["_timestamp"] for row in parsed)
    output: dict[str, dict[str, Any]] = {}
    for asset in ASSETS:
        asset_rows = sorted((row for row in parsed if row["asset"] == asset), key=lambda row: row["_timestamp"])
        if not asset_rows:
            continue
        rows_24h = [row for row in asset_rows if row["_timestamp"] >= latest_time - timedelta(hours=24)]
        rows_4h = [row for row in asset_rows if row["_timestamp"] >= latest_time - timedelta(hours=4)]
        span_hours = (asset_rows[-1]["_timestamp"] - asset_rows[0]["_timestamp"]).total_seconds() / 3600
        output[asset] = {
            "intraday_samples_4h": len(rows_4h),
            "intraday_samples_24h": len(rows_24h),
            "intraday_span_hours": span_hours,
            "intraday_taker_ratio_avg_4h": average_values(rows_4h, "taker_buy_sell_ratio_4h"),
            "intraday_taker_ratio_avg_24h": average_values(rows_24h, "taker_buy_sell_ratio_4h"),
            "intraday_book_imbalance_avg_4h": average_values(rows_4h, "orderbook_imbalance_0_5pct"),
            "intraday_book_imbalance_avg_24h": average_values(rows_24h, "orderbook_imbalance_0_5pct"),
            "intraday_funding_avg_24h": average_values(rows_24h, "funding_rate_pct"),
            "intraday_oi_change_4h_pct": period_change(rows_4h, "open_interest_usd_combined", 2.5),
            "intraday_oi_change_24h_pct": period_change(rows_24h, "open_interest_usd_combined", 18.0),
            "intraday_price_change_4h_pct": period_change(rows_4h, "price", 2.5),
            "intraday_price_change_24h_pct": period_change(rows_24h, "price", 18.0),
            "intraday_long_liquidation_usd_observed_24h": sum_values(rows_24h, "long_liquidation_usd_sample"),
            "intraday_short_liquidation_usd_observed_24h": sum_values(rows_24h, "short_liquidation_usd_sample"),
            "intraday_liquidation_events_observed_24h": sum_values(rows_24h, "liquidation_events_sample"),
        }
    return output


def enrich_asset_with_intraday(asset_row: dict[str, Any], summary: dict[str, Any]) -> dict[str, Any]:
    row = dict(asset_row)
    if not summary:
        row["_intraday"] = {}
        return row
    row["_intraday"] = summary
    if safe_int(summary.get("intraday_samples_4h"), 0) >= 3:
        for target, source in (
            ("taker_buy_sell_ratio_4h", "intraday_taker_ratio_avg_4h"),
            ("orderbook_imbalance_0_5pct", "intraday_book_imbalance_avg_4h"),
            ("oi_change_4h_pct", "intraday_oi_change_4h_pct"),
        ):
            value = safe_float(summary.get(source))
            if value is not None:
                row[target] = value
    if safe_int(summary.get("intraday_samples_24h"), 0) >= 8:
        for target, source in (
            ("taker_buy_sell_ratio_24h", "intraday_taker_ratio_avg_24h"),
            ("funding_rate_pct", "intraday_funding_avg_24h"),
            ("oi_change_24h_pct", "intraday_oi_change_24h_pct"),
            ("price_change_24h_pct", "intraday_price_change_24h_pct"),
        ):
            value = safe_float(summary.get(source))
            if value is not None:
                row[target] = value
        liq = dict(row.get("liquidation_sample", {})) if isinstance(row.get("liquidation_sample"), dict) else {}
        liq["long_liquidation_usd"] = summary.get("intraday_long_liquidation_usd_observed_24h")
        liq["short_liquidation_usd"] = summary.get("intraday_short_liquidation_usd_observed_24h")
        liq["events"] = summary.get("intraday_liquidation_events_observed_24h")
        row["liquidation_sample"] = liq
    return row

def technical_rows() -> dict[str, dict[str, str]]:
    rows = read_csv_rows(TECHNICAL_PATH)
    out: dict[str, dict[str, str]] = {}
    for row in rows:
        asset = normalize_asset(row.get("asset") or row.get("ticker"))
        if asset in ASSETS:
            out[asset] = row
    return out


def scanner_rows() -> dict[str, dict[str, str]]:
    rows = read_csv_rows(SCANNER_PATH)
    out: dict[str, dict[str, str]] = {}
    for row in rows:
        asset = normalize_asset(row.get("asset") or row.get("ticker"))
        if asset in ASSETS:
            out[asset] = row
    return out


def tracker_horizon_rows(horizon_days: int) -> dict[str, dict[str, str]]:
    rows = read_csv_rows(TRACKER_METRICS_PATH)
    out: dict[str, dict[str, str]] = {}
    for row in rows:
        asset = normalize_asset(row.get("asset"))
        horizon = safe_int(row.get("horizon_days"), -1)
        if asset in ASSETS and horizon == horizon_days:
            out[asset] = row
    return out


def tracker_30d_rows() -> dict[str, dict[str, str]]:
    return tracker_horizon_rows(30)


def tracker_7d_rows() -> dict[str, dict[str, str]]:
    return tracker_horizon_rows(7)


def sign_score(value: float, positive: float, negative: float, points: float = 1.0) -> float:
    if value >= positive:
        return points
    if value <= negative:
        return -points
    return 0.0


def field(asset_row: dict[str, Any], key: str) -> float | None:
    return safe_float(asset_row.get(key))


def score_asset(asset: str, row: dict[str, Any], technical: dict[str, str], calibration: dict[str, str]) -> dict[str, Any]:
    coverage = field(row, "data_coverage") or 0.0
    exchange_count = safe_int(row.get("exchange_count"), 0)
    exchange_available = row.get("exchange_available", {}) if isinstance(row.get("exchange_available"), dict) else {}
    exchanges = row.get("exchanges", {}) if isinstance(row.get("exchanges"), dict) else {}
    binance_row = exchanges.get("binance", {}) if isinstance(exchanges.get("binance"), dict) else {}
    bybit_row = exchanges.get("bybit", {}) if isinstance(exchanges.get("bybit"), dict) else {}
    kucoin_row = exchanges.get("kucoin", {}) if isinstance(exchanges.get("kucoin"), dict) else {}
    binance_book = binance_row.get("orderbook", {}) if isinstance(binance_row.get("orderbook"), dict) else {}
    bybit_book = bybit_row.get("orderbook", {}) if isinstance(bybit_row.get("orderbook"), dict) else {}
    kucoin_book = kucoin_row.get("orderbook", {}) if isinstance(kucoin_row.get("orderbook"), dict) else {}
    bullish_consensus_count = safe_int(row.get("bullish_consensus_count"), 0)
    bearish_consensus_count = safe_int(row.get("bearish_consensus_count"), 0)
    divergent_metric_count = safe_int(row.get("divergent_metric_count"), 0)
    funding = field(row, "funding_rate_pct")
    basis = field(row, "basis_pct")
    price_24h = field(row, "price_change_24h_pct")
    oi_4h = field(row, "oi_change_4h_pct")
    oi_24h = field(row, "oi_change_24h_pct")
    global_ls = field(row, "global_long_short_ratio")
    top_position_ls = field(row, "top_position_long_short_ratio")
    taker_1h = field(row, "taker_buy_sell_ratio_1h")
    taker_4h = field(row, "taker_buy_sell_ratio_4h")
    taker_24h = field(row, "taker_buy_sell_ratio_24h")
    book_025 = field(row, "orderbook_imbalance_0_25pct")
    book_05 = field(row, "orderbook_imbalance_0_5pct")
    book_10 = field(row, "orderbook_imbalance_1_0pct")

    liquidation = row.get("liquidation_sample", {}) if isinstance(row.get("liquidation_sample"), dict) else {}
    long_liq = safe_float(liquidation.get("long_liquidation_usd"), 0.0) or 0.0
    short_liq = safe_float(liquidation.get("short_liquidation_usd"), 0.0) or 0.0
    liq_total = long_liq + short_liq
    liq_events = safe_int(liquidation.get("events"), 0)
    largest_liq = safe_float(liquidation.get("largest_event_usd"), 0.0) or 0.0

    flow_parts: list[float] = []
    if taker_4h is not None:
        flow_parts.append(sign_score(taker_4h, 1.08, 0.92, 1.0))
    if taker_24h is not None:
        flow_parts.append(sign_score(taker_24h, 1.05, 0.95, 0.75))
    elif taker_1h is not None:
        flow_parts.append(sign_score(taker_1h, 1.10, 0.90, 0.5))
    if book_05 is not None:
        flow_parts.append(sign_score(book_05, 0.08, -0.08, 1.0))
    if book_10 is not None:
        flow_parts.append(sign_score(book_10, 0.06, -0.06, 0.5))
    flow_score = clamp(sum(flow_parts), -2.0, 2.0)

    derivatives_parts: list[float] = []
    if price_24h is not None and oi_24h is not None:
        if price_24h >= 1.0 and oi_24h >= 2.0:
            derivatives_parts.append(1.0)
        elif price_24h <= -1.0 and oi_24h >= 2.0:
            derivatives_parts.append(-1.0)
        elif price_24h <= -2.0 and oi_24h <= -3.0:
            derivatives_parts.append(0.5)  # deleveraging/capitulation: possible exhaustion
        elif price_24h >= 2.0 and oi_24h <= -3.0:
            derivatives_parts.append(-0.5)  # squeeze without new OI: fragile upside
    if funding is not None:
        derivatives_parts.append(sign_score(-funding, 0.03, -0.03, 0.75))
    if basis is not None:
        derivatives_parts.append(sign_score(-basis, 0.15, -0.15, 0.5))
    derivatives_score = clamp(sum(derivatives_parts), -2.0, 2.0)

    crowding_parts: list[float] = []
    if global_ls is not None:
        crowding_parts.append(1.0 if global_ls <= 0.75 else -1.0 if global_ls >= 1.80 else 0.0)
    if top_position_ls is not None:
        crowding_parts.append(0.5 if top_position_ls <= 0.75 else -0.5 if top_position_ls >= 1.80 else 0.0)
    crowding_score = clamp(sum(crowding_parts), -1.5, 1.5)

    liquidation_score = 0.0
    if liq_total >= LIQ_MIN_USD[asset]:
        if long_liq >= short_liq * 1.5:
            liquidation_score = -0.5
        elif short_liq >= long_liq * 1.5:
            liquidation_score = 0.5

    # Directional exchange consensus. This remains separate from the technical
    # confirmation text to avoid counting RSI/Fibonacci/Wyckoff twice.
    exchange_direction = flow_score + derivatives_score + crowding_score + liquidation_score

    rsi = safe_float(technical.get("rsi14"))
    fib_state = safe_text(technical.get("fib_state")).upper()
    fib_confluence = safe_text(technical.get("fib_confluence"))
    wyckoff = safe_text(technical.get("wyckoff")).lower()
    bullish_pattern = safe_text(technical.get("dominant_bullish_pattern"))
    bullish_status = safe_text(technical.get("dominant_bullish_status")).upper()
    bearish_pattern = safe_text(technical.get("dominant_bearish_pattern"))
    bearish_status = safe_text(technical.get("dominant_bearish_status")).upper()
    price = field(row, "price") or safe_float(technical.get("price"))
    support = safe_float(technical.get("support"))
    resistance = safe_float(technical.get("resistance"))

    if rsi is None:
        rsi_confirmation = "RSI non disponibile nel file tecnico."
        rsi_score = 0.0
    elif rsi <= 35 and exchange_direction > 0.75:
        rsi_confirmation = "RSI debole/ipervenduto con flusso exchange in recupero: possibile esaurimento della vendita."
        rsi_score = 0.5
    elif rsi <= 35 and exchange_direction < -0.75:
        rsi_confirmation = "RSI debole ma CVD/taker flow e leva restano negativi: ipervenduto non ancora confermato."
        rsi_score = -0.5
    elif rsi >= 65 and (exchange_direction < -0.75 or crowding_score < -0.5):
        rsi_confirmation = "RSI alto con flusso debole o long affollati: rischio di scarico."
        rsi_score = -0.5
    elif rsi >= 65 and exchange_direction > 0.75 and crowding_score >= 0:
        rsi_confirmation = "RSI alto ma sostenuto da acquisti e leva non estrema: momentum ancora credibile."
        rsi_score = 0.5
    else:
        rsi_confirmation = "RSI in zona non estrema o flusso exchange non abbastanza netto."
        rsi_score = 0.0

    fib_positive_states = {"TENUTO", "RECUPERATO", "RECLAIMED", "HELD"}
    fib_negative_states = {"PERSO", "RESPINTO", "LOST", "REJECTED"}
    if not fib_state:
        fib_confirmation = "Fibonacci strutturato non disponibile."
        fib_score = 0.0
    elif fib_state in fib_positive_states and exchange_direction > 0.75:
        fib_confirmation = f"Fibonacci {fib_state.lower()} con acquisti/assorbimento coerenti: conferma positiva."
        fib_score = 0.5
    elif fib_state in fib_negative_states and exchange_direction < -0.75:
        fib_confirmation = f"Fibonacci {fib_state.lower()} con vendite e leva coerenti: conferma negativa."
        fib_score = -0.5
    elif fib_state == "TESTATO":
        fib_confirmation = "Livello Fibonacci soltanto testato: order book e taker flow non bastano ancora per dichiararlo tenuto o perso."
        fib_score = 0.0
    else:
        fib_confirmation = f"Fibonacci {fib_state.lower()}; nessuna conferma exchange netta."
        fib_score = 0.0
    if fib_confluence and "nessuna" not in fib_confluence.lower():
        fib_confirmation += f" Confluenza tecnica dichiarata: {fib_confluence}."

    if "accumul" in wyckoff or "spring" in wyckoff:
        if flow_score >= 1.0 and derivatives_score >= -0.5:
            wyckoff_confirmation = "Possibile accumulazione/spring sostenuto da pressione compratrice o assorbimento."
            wyckoff_score = 0.75
        elif flow_score <= -1.0:
            wyckoff_confirmation = "Possibile accumulazione non confermata: il flusso aggressivo resta venditore."
            wyckoff_score = -0.5
        else:
            wyckoff_confirmation = "Possibile accumulazione ancora neutrale nei dati exchange."
            wyckoff_score = 0.0
    elif "distrib" in wyckoff or "markdown" in wyckoff or "debole" in wyckoff:
        if flow_score <= -1.0 or derivatives_score <= -1.0:
            wyckoff_confirmation = "Distribuzione/markdown confermato da vendite aggressive e/o nuovo OI ribassista."
            wyckoff_score = -0.75
        elif flow_score >= 1.0:
            wyckoff_confirmation = "Markdown non pienamente confermato: compare assorbimento compratore."
            wyckoff_score = 0.5
        else:
            wyckoff_confirmation = "Fase Wyckoff debole ma senza conferma exchange netta."
            wyckoff_score = 0.0
    else:
        wyckoff_confirmation = "Fase Wyckoff non abbastanza chiara per una conferma exchange."
        wyckoff_score = 0.0

    active_states = {"ATTIVO", "CONFERMATO RECENTE", "MATURO"}
    if bullish_pattern and bullish_status in active_states and exchange_direction >= 1.0:
        pattern_confirmation = f"{bullish_pattern} {bullish_status.lower()} sostenuto dal flusso exchange."
        pattern_score = 0.5
    elif bearish_pattern and bearish_status in active_states and exchange_direction <= -1.0:
        pattern_confirmation = f"{bearish_pattern} {bearish_status.lower()} sostenuto dal flusso exchange."
        pattern_score = -0.5
    elif bullish_status == "CANDIDATO" or bearish_status == "CANDIDATO":
        pattern_confirmation = "I pattern candidati restano non operativi: i dati exchange possono solo preparare la conferma."
        pattern_score = 0.0
    else:
        pattern_confirmation = "Nessun pattern attivo con conferma exchange sufficiente."
        pattern_score = 0.0

    nearest_bid_wall, nearest_ask_wall = liquidity_wall_summary(row, price)
    near_resistance = price is not None and resistance not in (None, 0) and abs(price / resistance - 1.0) <= 0.02
    near_support = price is not None and support not in (None, 0) and abs(price / support - 1.0) <= 0.02
    if near_resistance and exchange_direction >= 1.0 and (book_05 or 0) >= 0:
        breakout_quality = "Resistenza vicina con acquisti aggressivi: breakout più credibile, ma serve chiusura sopra il livello."
        breakout_score = 0.5
    elif near_resistance and (crowding_score <= -0.5 or exchange_direction < 0):
        breakout_quality = "Resistenza vicina ma long affollati/flusso debole: rischio di falso breakout o squeeze breve."
        breakout_score = -0.5
    elif near_support and exchange_direction <= -1.0 and (book_05 or 0) <= 0:
        breakout_quality = "Supporto vicino con vendite aggressive: breakdown più credibile."
        breakout_score = -0.5
    elif near_support and exchange_direction >= 1.0:
        breakout_quality = "Supporto vicino con assorbimento/acquisti: tenuta più credibile."
        breakout_score = 0.5
    else:
        breakout_quality = "Prezzo non abbastanza vicino a un livello chiave o flusso non netto."
        breakout_score = 0.0

    technical_confirmation_score = clamp(
        rsi_score + fib_score + wyckoff_score + pattern_score + breakout_score,
        -1.5,
        1.5,
    )

    raw_score = clamp(exchange_direction + technical_confirmation_score * 0.5, -6.0, 6.0)
    category_scores = [flow_score, derivatives_score, crowding_score, liquidation_score, technical_confirmation_score]
    positive_categories = sum(score >= 0.75 for score in category_scores)
    negative_categories = sum(score <= -0.75 for score in category_scores)

    if coverage < 0.60 or exchange_count < 2:
        candidate_global_score = 0
    elif raw_score >= 2.5 and positive_categories >= 2 and bullish_consensus_count >= 1 and divergent_metric_count <= 1:
        candidate_global_score = 1
    elif raw_score <= -2.5 and negative_categories >= 2 and bearish_consensus_count >= 1 and divergent_metric_count <= 1:
        candidate_global_score = -1
    else:
        candidate_global_score = 0

    calibration_controls = safe_int(calibration.get("controls"), 0)
    calibration_accuracy = safe_float(calibration.get("accuracy_direction_pct"))
    calibration_signed_return = safe_float(calibration.get("avg_direction_adjusted_return_pct"))
    global_score = 0
    if calibration_controls < 30:
        global_activation_status = "LOCKED / RACCOLTA 7G"
    elif calibration_accuracy is None or calibration_signed_return is None:
        global_activation_status = "LOCKED / METRICHE 7G INCOMPLETE"
    elif calibration_accuracy >= 55.0 and calibration_signed_return > 0:
        global_score = candidate_global_score
        global_activation_status = "ACTIVE / CALIBRATO 7G"
    elif calibration_accuracy < 45.0 or calibration_signed_return <= 0:
        global_activation_status = "LOCKED / MODULO 7G DEBOLE"
    else:
        global_activation_status = "LOCKED / VANTAGGIO 7G NON DIMOSTRATO"

    if global_score > 0:
        bias = "POSITIVA / PESO GLOBALE CALIBRATO"
    elif global_score < 0:
        bias = "NEGATIVA / PESO GLOBALE CALIBRATO"
    elif candidate_global_score > 0:
        bias = "POSITIVA / CANDIDATA, ANCORA NON PESATA"
    elif candidate_global_score < 0:
        bias = "NEGATIVA / CANDIDATA, ANCORA NON PESATA"
    elif raw_score >= 1.0:
        bias = "LEGGERMENTE POSITIVA / NON PESATA"
    elif raw_score <= -1.0:
        bias = "LEGGERMENTE NEGATIVA / NON PESATA"
    else:
        bias = "MISTA / NEUTRALE"

    agreement = max(positive_categories, negative_categories)
    if coverage >= 0.85 and exchange_count == 3 and agreement >= 3 and divergent_metric_count == 0:
        confidence = "ALTA"
    elif coverage >= 0.70 and exchange_count >= 2 and agreement >= 2 and divergent_metric_count <= 1:
        confidence = "MEDIA"
    else:
        confidence = "BASSA"

    detail = (
        f"Flow {flow_score:+.2f}, derivati {derivatives_score:+.2f}, affollamento {crowding_score:+.2f}, "
        f"liquidazioni campione {liquidation_score:+.2f}, conferme tecniche {technical_confirmation_score:+.2f}; "
        f"exchange {exchange_count}/3, copertura {coverage * 100:.0f}%, consenso bull {bullish_consensus_count}, "
        f"bear {bearish_consensus_count}, divergenze {divergent_metric_count}; candidato {candidate_global_score:+d}, "
        f"peso Global {global_score:+d} ({global_activation_status})."
    )

    return {
        "generated_utc": utc_now_iso(),
        "asset": asset,
        "price": price,
        "data_coverage": coverage,
        "exchange_count": exchange_count,
        "binance_available": bool(exchange_available.get("binance")),
        "bybit_available": bool(exchange_available.get("bybit")),
        "kucoin_available": bool(exchange_available.get("kucoin")),
        "raw_score": round(raw_score, 4),
        "candidate_global_score": candidate_global_score,
        "global_score": global_score,
        "global_activation_status": global_activation_status,
        "calibration_controls_7d": calibration_controls,
        "calibration_accuracy_7d": calibration_accuracy,
        "calibration_signed_return_7d": calibration_signed_return,
        "bias": bias,
        "confidence": confidence,
        "flow_score": round(flow_score, 4),
        "derivatives_score": round(derivatives_score, 4),
        "crowding_score": round(crowding_score, 4),
        "liquidation_score": round(liquidation_score, 4),
        "technical_confirmation_score": round(technical_confirmation_score, 4),
        "funding_rate_pct": funding,
        "basis_pct": basis,
        "price_change_24h_pct": price_24h,
        "open_interest_usd_combined": field(row, "open_interest_usd_combined"),
        "oi_change_4h_pct": oi_4h,
        "oi_change_24h_pct": oi_24h,
        "global_long_short_ratio": global_ls,
        "top_account_long_short_ratio": field(row, "top_account_long_short_ratio"),
        "top_position_long_short_ratio": top_position_ls,
        "taker_buy_sell_ratio_1h": taker_1h,
        "taker_buy_sell_ratio_4h": taker_4h,
        "taker_buy_sell_ratio_24h": taker_24h,
        "orderbook_imbalance_0_25pct": book_025,
        "orderbook_imbalance_0_5pct": book_05,
        "orderbook_imbalance_1_0pct": book_10,
        "spread_bps": field(row, "spread_bps"),
        "intraday_samples_4h": safe_int((row.get("_intraday") or {}).get("intraday_samples_4h"), 0),
        "intraday_samples_24h": safe_int((row.get("_intraday") or {}).get("intraday_samples_24h"), 0),
        "intraday_span_hours": safe_float((row.get("_intraday") or {}).get("intraday_span_hours")),
        "intraday_taker_ratio_avg_4h": safe_float((row.get("_intraday") or {}).get("intraday_taker_ratio_avg_4h")),
        "intraday_taker_ratio_avg_24h": safe_float((row.get("_intraday") or {}).get("intraday_taker_ratio_avg_24h")),
        "intraday_book_imbalance_avg_4h": safe_float((row.get("_intraday") or {}).get("intraday_book_imbalance_avg_4h")),
        "intraday_book_imbalance_avg_24h": safe_float((row.get("_intraday") or {}).get("intraday_book_imbalance_avg_24h")),
        "intraday_funding_avg_24h": safe_float((row.get("_intraday") or {}).get("intraday_funding_avg_24h")),
        "intraday_oi_change_4h_pct": safe_float((row.get("_intraday") or {}).get("intraday_oi_change_4h_pct")),
        "intraday_oi_change_24h_pct": safe_float((row.get("_intraday") or {}).get("intraday_oi_change_24h_pct")),
        "intraday_price_change_4h_pct": safe_float((row.get("_intraday") or {}).get("intraday_price_change_4h_pct")),
        "intraday_price_change_24h_pct": safe_float((row.get("_intraday") or {}).get("intraday_price_change_24h_pct")),
        "intraday_long_liquidation_usd_observed_24h": safe_float((row.get("_intraday") or {}).get("intraday_long_liquidation_usd_observed_24h")),
        "intraday_short_liquidation_usd_observed_24h": safe_float((row.get("_intraday") or {}).get("intraday_short_liquidation_usd_observed_24h")),
        "intraday_liquidation_events_observed_24h": safe_float((row.get("_intraday") or {}).get("intraday_liquidation_events_observed_24h")),
        "bullish_consensus_count": bullish_consensus_count,
        "bearish_consensus_count": bearish_consensus_count,
        "divergent_metric_count": divergent_metric_count,
        "binance_funding_rate_pct": safe_float(binance_row.get("funding_rate_pct")),
        "bybit_funding_rate_pct": safe_float(bybit_row.get("funding_rate_pct")),
        "kucoin_funding_rate_pct": safe_float(kucoin_row.get("funding_rate_pct")),
        "binance_open_interest_usd": safe_float(binance_row.get("open_interest_usd")),
        "bybit_open_interest_usd": safe_float(bybit_row.get("open_interest_usd")),
        "kucoin_open_interest_usd": safe_float(kucoin_row.get("open_interest_usd")),
        "binance_taker_ratio": safe_float(binance_row.get("taker_buy_sell_ratio_4h")),
        "bybit_taker_ratio": safe_float(bybit_row.get("taker_buy_sell_ratio_recent")),
        "kucoin_taker_ratio": safe_float(kucoin_row.get("taker_buy_sell_ratio_recent")),
        "binance_book_imbalance_0_5pct": safe_float(binance_book.get("imbalance_0_5pct")),
        "bybit_book_imbalance_0_5pct": safe_float(bybit_book.get("imbalance_0_5pct")),
        "kucoin_book_imbalance_0_5pct": safe_float(kucoin_book.get("imbalance_0_5pct")),
        "long_liquidation_usd_sample": long_liq,
        "short_liquidation_usd_sample": short_liq,
        "liquidation_events_sample": liq_events,
        "largest_liquidation_usd_sample": largest_liq,
        "wyckoff_confirmation": wyckoff_confirmation,
        "fibonacci_confirmation": fib_confirmation,
        "rsi_confirmation": rsi_confirmation,
        "pattern_confirmation": pattern_confirmation,
        "breakout_quality": breakout_quality,
        "liquidity_map": f"{nearest_bid_wall}; {nearest_ask_wall}",
        "detail": detail,
    }


def liquidity_wall_summary(row: dict[str, Any], price: float | None) -> tuple[str, str]:
    bid_candidates: list[tuple[str, dict[str, Any]]] = []
    ask_candidates: list[tuple[str, dict[str, Any]]] = []
    for exchange in ("binance", "bybit", "kucoin"):
        bid = row.get(f"{exchange}_bid_wall")
        ask = row.get(f"{exchange}_ask_wall")
        if isinstance(bid, dict) and safe_float(bid.get("notional")) is not None:
            bid_candidates.append((exchange, bid))
        if isinstance(ask, dict) and safe_float(ask.get("notional")) is not None:
            ask_candidates.append((exchange, ask))

    def describe(candidates: list[tuple[str, dict[str, Any]]], label: str) -> str:
        if not candidates:
            return f"{label}: n/a"
        exchange, wall = max(candidates, key=lambda item: safe_float(item[1].get("notional"), 0.0) or 0.0)
        wall_price = safe_float(wall.get("price"))
        notional = safe_float(wall.get("notional"))
        distance = safe_float(wall.get("distance_pct"))
        multiple = safe_float(wall.get("multiple_median"))
        return (
            f"{label} {exchange} @ {fmt_price_raw(wall_price)} "
            f"({fmt_pct(distance)}, {fmt_usd(notional)}, {multiple:.1f}x mediana)"
            if multiple is not None
            else f"{label} {exchange} @ {fmt_price_raw(wall_price)} ({fmt_pct(distance)}, {fmt_usd(notional)})"
        )

    return describe(bid_candidates, "muro bid"), describe(ask_candidates, "muro ask")


def prediction_overlay(
    asset: str,
    exchange_metric: dict[str, Any],
    scanner: dict[str, str],
    tracker: dict[str, str],
) -> dict[str, Any]:
    raw_positive = safe_float(scanner.get("positive_cases_30d"))
    raw_return = safe_float(scanner.get("return_p50_pct"))
    controls = safe_int(tracker.get("controls"), 0)
    accuracy = safe_float(tracker.get("accuracy_direction_pct"))
    exchange_score = safe_int(exchange_metric.get("candidate_global_score"), 0)

    weight = 0.0
    status = "RACCOLTA DATI"
    note = "Overlay non attivo: servono almeno 30 controlli maturati a 30 giorni."
    if controls >= 30 and accuracy is not None:
        if accuracy >= 55.0:
            # 55% -> 0.25, 70%+ -> 1.0. This is deliberately conservative.
            weight = clamp((accuracy - 50.0) / 20.0, 0.0, 1.0)
            status = "ATTIVO / CALIBRATO"
            note = "L'overlay usa soltanto l'affidabilità osservata del modulo exchange."
        elif accuracy < 45.0:
            status = "SOSPESO / MODULO DEBOLE"
            note = "Accuratezza exchange sotto 45%: nessun aggiustamento automatico."
        else:
            status = "NEUTRO / VANTAGGIO NON DIMOSTRATO"
            note = "Campione sufficiente, ma accuratezza troppo vicina al caso."

    adjusted_positive = raw_positive
    adjusted_return = raw_return
    if raw_positive is not None and exchange_score and weight > 0:
        adjusted_positive = clamp(raw_positive + exchange_score * 5.0 * weight, 1.0, 99.0)
    if raw_return is not None and exchange_score and weight > 0:
        adjusted_return = raw_return + exchange_score * 1.5 * weight

    return {
        "generated_utc": utc_now_iso(),
        "asset": asset,
        "raw_positive_rate_30d": raw_positive,
        "raw_return_p50_30d": raw_return,
        "exchange_score": exchange_score,
        "tracker_controls_30d": controls,
        "tracker_accuracy_30d": accuracy,
        "overlay_status": status,
        "overlay_weight": round(weight, 4),
        "adjusted_positive_rate_30d": adjusted_positive,
        "adjusted_return_p50_30d": adjusted_return,
        "note": note,
    }


def update_history(metrics: list[dict[str, Any]], overlays: list[dict[str, Any]]) -> list[dict[str, str]]:
    existing = read_csv_rows(HISTORY_PATH)
    existing_extra_fields: list[str] = []
    if existing:
        existing_extra_fields = [field for field in existing[0].keys() if field not in HISTORY_BASE_FIELDS]
    history_fields = list(HISTORY_BASE_FIELDS) + existing_extra_fields
    keys = {(row.get("signal_date", ""), normalize_asset(row.get("asset"))) for row in existing}
    overlay_map = {row["asset"]: row for row in overlays}
    now = utc_now_iso()
    for metric in metrics:
        asset = metric["asset"]
        key = (utc_date(), asset)
        if key in keys:
            # Freeze the first daily snapshot, matching the rest of the scanner.
            continue
        overlay = overlay_map.get(asset, {})
        row = {
            "signal_date": utc_date(),
            "asset": asset,
            "price": metric.get("price"),
            "raw_score": metric.get("raw_score"),
            "candidate_global_score": metric.get("candidate_global_score"),
            "global_score": metric.get("global_score"),
            "global_activation_status": metric.get("global_activation_status"),
            "bias": metric.get("bias"),
            "confidence": metric.get("confidence"),
            "data_coverage": metric.get("data_coverage"),
            "exchange_count": metric.get("exchange_count"),
            "bullish_consensus_count": metric.get("bullish_consensus_count"),
            "bearish_consensus_count": metric.get("bearish_consensus_count"),
            "divergent_metric_count": metric.get("divergent_metric_count"),
            "funding_rate_pct": metric.get("funding_rate_pct"),
            "basis_pct": metric.get("basis_pct"),
            "price_change_24h_pct": metric.get("price_change_24h_pct"),
            "open_interest_usd_combined": metric.get("open_interest_usd_combined"),
            "oi_change_4h_pct": metric.get("oi_change_4h_pct"),
            "oi_change_24h_pct": metric.get("oi_change_24h_pct"),
            "global_long_short_ratio": metric.get("global_long_short_ratio"),
            "top_position_long_short_ratio": metric.get("top_position_long_short_ratio"),
            "taker_buy_sell_ratio_4h": metric.get("taker_buy_sell_ratio_4h"),
            "taker_buy_sell_ratio_24h": metric.get("taker_buy_sell_ratio_24h"),
            "orderbook_imbalance_0_5pct": metric.get("orderbook_imbalance_0_5pct"),
            "orderbook_imbalance_1_0pct": metric.get("orderbook_imbalance_1_0pct"),
            "long_liquidation_usd_sample": metric.get("long_liquidation_usd_sample"),
            "short_liquidation_usd_sample": metric.get("short_liquidation_usd_sample"),
            "liquidation_events_sample": metric.get("liquidation_events_sample"),
            "scanner_positive_rate_30d": overlay.get("raw_positive_rate_30d"),
            "scanner_return_p50_30d": overlay.get("raw_return_p50_30d"),
            "overlay_status": overlay.get("overlay_status"),
            "overlay_weight": overlay.get("overlay_weight"),
            "adjusted_positive_rate_30d": overlay.get("adjusted_positive_rate_30d"),
            "adjusted_return_p50_30d": overlay.get("adjusted_return_p50_30d"),
            "created_utc": now,
        }
        existing.append({field: row.get(field, "") for field in history_fields})
        keys.add(key)

    existing.sort(key=lambda row: (row.get("signal_date", ""), normalize_asset(row.get("asset"))))
    write_csv(HISTORY_PATH, existing, history_fields)
    return existing


def make_history_charts(history: list[dict[str, str]]) -> dict[str, str]:
    output: dict[str, str] = {}
    try:
        import matplotlib.pyplot as plt
    except Exception:
        return output

    for asset in ASSETS:
        rows = [row for row in history if normalize_asset(row.get("asset")) == asset]
        rows = sorted(rows, key=lambda row: row.get("signal_date", ""))
        if len(rows) < 2:
            continue
        dates = [row.get("signal_date", "") for row in rows]
        raw_scores = [safe_float(row.get("raw_score"), 0.0) or 0.0 for row in rows]
        taker = [safe_float(row.get("taker_buy_sell_ratio_4h")) for row in rows]
        book = [safe_float(row.get("orderbook_imbalance_0_5pct")) for row in rows]

        fig, ax = plt.subplots(figsize=(10, 5.2))
        ax.plot(dates, raw_scores, marker="o", label="Exchange raw score")
        ax.axhline(0, linewidth=1)
        ax.set_ylabel("Score")
        ax.set_title(f"{asset} — microstruttura exchange nel tempo")
        ax.tick_params(axis="x", rotation=45)
        ax2 = ax.twinx()
        ax2.plot(dates, [value if value is not None else math.nan for value in taker], marker=".", label="Taker buy/sell 4h")
        ax2.plot(dates, [value if value is not None else math.nan for value in book], marker=".", label="Book imbalance 0.5%")
        ax2.set_ylabel("Ratio / imbalance")
        handles1, labels1 = ax.get_legend_handles_labels()
        handles2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(handles1 + handles2, labels1 + labels2, loc="best")
        fig.tight_layout()
        path = REPORTS_DIR / f"exchange_microstructure_{asset}.png"
        fig.savefig(path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        output[asset] = path.name
    return output


def fmt_pct(value: Any, decimals: int = 2) -> str:
    number = safe_float(value)
    if number is None:
        return "n/a"
    return f"{number:+.{decimals}f}%".replace(".", ",")


def fmt_ratio(value: Any, decimals: int = 2) -> str:
    number = safe_float(value)
    return "n/a" if number is None else f"{number:.{decimals}f}".replace(".", ",")


def fmt_score(value: Any) -> str:
    number = safe_float(value)
    if number is None:
        return "0"
    return f"{number:+.2f}".replace(".", ",")


def fmt_int_score(value: Any) -> str:
    number = safe_int(value, 0)
    return f"+{number}" if number > 0 else str(number)


def fmt_usd(value: Any) -> str:
    number = safe_float(value)
    if number is None:
        return "n/a"
    if abs(number) >= 1_000_000_000:
        return f"{number / 1_000_000_000:.2f} mld $".replace(".", ",")
    if abs(number) >= 1_000_000:
        return f"{number / 1_000_000:.2f} mln $".replace(".", ",")
    if abs(number) >= 1_000:
        return f"{number / 1_000:.1f} mila $".replace(".", ",")
    return f"{number:.0f} $".replace(".", ",")


def classify_health_record(record: dict[str, Any]) -> str:
    if not isinstance(record, dict):
        return "MISSING"
    if record.get("ok") is True:
        return "OK"
    explicit = safe_text(record.get("state")).upper()
    if explicit:
        return explicit
    status_code = safe_int(record.get("status_code"), 0)
    error = safe_text(record.get("error")).lower()
    if status_code == 451:
        return "GEO_BLOCKED"
    if status_code == 403 and any(token in error for token in ("country", "restricted location", "eligibility")):
        return "GEO_BLOCKED"
    if status_code == 429:
        return "RATE_LIMITED"
    if "timeout" in error:
        return "TIMEOUT"
    if status_code:
        return "HTTP_ERROR"
    return "MISSING"


def exchange_health_status(health: dict[str, Any], asset: str, exchange: str) -> str:
    assets = health.get("assets", {}) if isinstance(health, dict) else {}
    asset_row = assets.get(asset, {}) if isinstance(assets, dict) else {}
    exchange_row = asset_row.get(exchange, {}) if isinstance(asset_row, dict) else {}
    states = [classify_health_record(row) for row in exchange_row.values() if isinstance(row, dict)]
    if "OK" in states:
        return "OK"
    for candidate in ("GEO_BLOCKED", "RATE_LIMITED", "TIMEOUT", "HTTP_ERROR", "ERROR", "DISABLED"):
        if candidate in states:
            return candidate
    top = health.get("exchange_status", {}) if isinstance(health, dict) else {}
    value = safe_text(top.get(exchange)).upper() if isinstance(top, dict) else ""
    return value or "MISSING"


def status_label(state: str) -> str:
    labels = {
        "OK": "OK",
        "GEO_BLOCKED": "BLOCCO GEOGRAFICO",
        "RATE_LIMITED": "RATE LIMIT",
        "TIMEOUT": "TIMEOUT",
        "HTTP_ERROR": "ERRORE HTTP",
        "ERROR": "ERRORE",
        "DISABLED": "DISABILITATO",
        "MISSING": "MANCANTE",
    }
    return labels.get(safe_text(state).upper(), safe_text(state, "MANCANTE"))


def compact_error(value: Any, limit: int = 180) -> str:
    text = " ".join(safe_text(value).split())
    return text if len(text) <= limit else text[: limit - 1] + "…"


def render_source_diagnostics(health: dict[str, Any], storage: dict[str, Any]) -> str:
    lines = [
        "# Diagnostica fonti exchange",
        "",
        f"Generato: {utc_now_text()}",
        "",
        f"- Stato generale: **{safe_text(health.get('status'), 'n/a')}**",
        f"- Modalità collector: **{safe_text(health.get('collector_mode'), 'non dichiarata')}**",
        f"- Coppie exchange/asset disponibili: **{safe_int(health.get('available_exchange_asset_pairs'))}/{safe_int(health.get('total_exchange_asset_pairs'))}**",
        f"- Storage ripristinato: **{safe_text(storage.get('status'), safe_text(storage.get('restore_status'), 'n/a'))}**",
        "",
        "## Stato sintetico",
        "",
    ]
    summary_rows = []
    for exchange in ("binance", "bybit", "kucoin"):
        states = [exchange_health_status(health, asset, exchange) for asset in ASSETS]
        state = "OK" if "OK" in states else next((x for x in states if x != "MISSING"), "MISSING")
        summary_rows.append([exchange.capitalize(), status_label(state), ", ".join(f"{asset}: {status_label(exchange_health_status(health, asset, exchange))}" for asset in ASSETS)])
    lines += [md_table(["Exchange", "Stato", "Asset"], summary_rows), "", "## Endpoint", ""]

    endpoint_rows: list[list[str]] = []
    assets = health.get("assets", {}) if isinstance(health, dict) else {}
    for asset in ASSETS:
        asset_row = assets.get(asset, {}) if isinstance(assets, dict) else {}
        for exchange in ("binance", "bybit", "kucoin"):
            exchange_row = asset_row.get(exchange, {}) if isinstance(asset_row, dict) else {}
            if not isinstance(exchange_row, dict) or not exchange_row:
                endpoint_rows.append([asset, exchange.capitalize(), "n/a", "MANCANTE", "n/a", "Nessun record diagnostico"])
                continue
            for endpoint, record in exchange_row.items():
                if not isinstance(record, dict):
                    continue
                endpoint_rows.append([
                    asset,
                    exchange.capitalize(),
                    str(endpoint),
                    status_label(classify_health_record(record)),
                    str(record.get("status_code") or "n/a"),
                    compact_error(record.get("error") or "OK"),
                ])
    lines += [md_table(["Asset", "Exchange", "Endpoint", "Stato", "HTTP", "Dettaglio"], endpoint_rows), ""]

    streams = health.get("liquidation_streams", {}) if isinstance(health, dict) else {}
    lines += ["## Stream liquidazioni", ""]
    stream_rows = []
    for exchange in ("binance", "bybit"):
        row = streams.get(exchange, {}) if isinstance(streams, dict) else {}
        stream_rows.append([
            exchange.capitalize(),
            status_label(classify_health_record(row)),
            str(safe_int(row.get("messages"), 0)),
            compact_error(row.get("error") or "OK"),
        ])
    lines += [md_table(["Exchange", "Stato", "Messaggi", "Dettaglio"], stream_rows), ""]

    if any(exchange_health_status(health, asset, exchange) == "GEO_BLOCKED" for asset in ASSETS for exchange in ("binance", "bybit")):
        lines += [
            "## Lettura",
            "",
            "Almeno una fonte è bloccata geograficamente dall'IP del collector. Il programma non tenta proxy o aggiramenti. "
            "Per usare quella fonte serve eseguire il collector su un host situato in una giurisdizione dove l'API sia consentita, oppure lasciarla disabilitata.",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def fmt_price(asset: str, value: Any) -> str:
    number = safe_float(value)
    if number is None:
        return "n/a"
    if asset == "BTC":
        return f"{number:,.0f} $".replace(",", ".")
    if asset == "DOGE":
        return f"{number:.5f} $"
    return f"{number:.2f} $".replace(".", ",")


def fmt_price_raw(value: Any) -> str:
    number = safe_float(value)
    if number is None:
        return "n/a"
    if number >= 1000:
        return f"{number:,.0f}".replace(",", ".")
    if number < 1:
        return f"{number:.5f}"
    return f"{number:.2f}".replace(".", ",")


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    lines.extend("| " + " | ".join(str(cell).replace("|", "/") for cell in row) + " |" for row in rows)
    return "\n".join(lines)


def render_report(
    metrics: list[dict[str, Any]],
    overlays: list[dict[str, Any]],
    health: dict[str, Any],
    chart_names: dict[str, str],
    sample_seconds: int,
    storage: dict[str, Any],
) -> str:
    metric_map = {row["asset"]: row for row in metrics}
    overlay_map = {row["asset"]: row for row in overlays}
    summary_rows: list[list[str]] = []
    for asset in ASSETS:
        row = metric_map[asset]
        summary_rows.append(
            [
                asset,
                fmt_price(asset, row.get("price")),
                str(safe_int(row.get("exchange_count"))),
                fmt_int_score(row.get("candidate_global_score")),
                fmt_int_score(row.get("global_score")),
                row.get("bias", ""),
                row.get("confidence", ""),
                f"{(safe_float(row.get('data_coverage'), 0.0) or 0.0) * 100:.0f}%",
                fmt_pct(row.get("funding_rate_pct"), 4),
                fmt_pct(row.get("oi_change_24h_pct")),
                fmt_ratio(row.get("taker_buy_sell_ratio_4h")),
                fmt_pct((safe_float(row.get("orderbook_imbalance_0_5pct"), 0.0) or 0.0) * 100.0),
                fmt_usd(row.get("long_liquidation_usd_sample")),
                fmt_usd(row.get("short_liquidation_usd_sample")),
            ]
        )

    lines = [
        "# Dati exchange, liquidità e leva",
        "",
        f"Generato: {utc_now_text()}",
        "",
        "Questo modulo legge Binance Futures, Bybit e KuCoin Futures per aggiungere microstruttura, leva e flussi reali allo scanner.",
        "Non modifica la formula matematica di RSI, Fibonacci o Wyckoff: controlla se quei segnali sono sostenuti da acquisti, vendite, OI, funding e liquidità.",
        "",
        "**Limite importante:** gli exchange non pubblicano la mappa completa dei prezzi di liquidazione di tutti gli utenti. "
        f"Le liquidazioni qui sotto sono eventi realmente osservati in un campione pubblico di circa {sample_seconds} secondi; "
        "le zone future di liquidazione restano stime di pressione, non dati certi delle singole posizioni.",
        "",
        "Diagnostica completa: [exchange_source_diagnostics.md](exchange_source_diagnostics.md)",
        "",
        "## Sintesi",
        "",
        md_table(
            [
                "Asset",
                "Prezzo",
                "Exchange",
                "Segnale candidato",
                "Peso Global",
                "Bias exchange",
                "Confidenza",
                "Copertura",
                "Funding",
                "OI 24h",
                "Taker flow (campione/4h)",
                "Book 0,5%",
                "Liq long campione",
                "Liq short campione",
            ],
            summary_rows,
        ),
        "",
        "Il segnale candidato è limitato a **±1**, ma il peso nel Global resta **0** finché il tracker a 7 giorni non raggiunge 30 controlli, almeno 55% di accuratezza e return corretto direzione positivo. Un singolo muro o funding non basta.",
        "",
        "La colonna taker usa un campione recente nel primo run. Dopo almeno 3 fotografie nelle ultime 4 ore viene sostituita automaticamente dalla media intraday 4h.",
        "",
        "## Dati separati per exchange",
        "",
    ]

    exchange_rows: list[list[str]] = []
    for asset in ASSETS:
        row = metric_map[asset]
        for exchange in ("binance", "bybit", "kucoin"):
            available = row.get(f"{exchange}_available")
            exchange_rows.append(
                [
                    asset,
                    exchange.capitalize(),
                    status_label(row.get(f"{exchange}_status") or ("OK" if available else "MISSING")),
                    fmt_pct(row.get(f"{exchange}_funding_rate_pct"), 4),
                    fmt_usd(row.get(f"{exchange}_open_interest_usd")),
                    fmt_ratio(row.get(f"{exchange}_taker_ratio")),
                    fmt_pct((safe_float(row.get(f"{exchange}_book_imbalance_0_5pct"), 0.0) or 0.0) * 100.0),
                ]
            )
    lines += [
        md_table(["Asset", "Exchange", "Stato", "Funding", "Open interest", "Taker flow", "Book 0,5%"], exchange_rows),
        "",
        "KuCoin contribuisce a funding, open interest, trade aggressivi e order book. Non viene inventato un long/short ratio pubblico né un feed pubblico completo delle liquidazioni quando l'API non li espone.",
        "",
        "## Conferme per indicatori tecnici",
        "",
    ]

    for asset in ASSETS:
        row = metric_map[asset]
        lines += [
            f"### {asset}",
            "",
            f"- Score grezzo exchange: **{fmt_score(row.get('raw_score'))}**; candidato: **{fmt_int_score(row.get('candidate_global_score'))}**; peso Global: **{fmt_int_score(row.get('global_score'))}**.",
            f"- Attivazione Global: **{row.get('global_activation_status')}** — controlli 7g {safe_int(row.get('calibration_controls_7d'))}, accuratezza {fmt_pct(row.get('calibration_accuracy_7d'))}.",
            f"- Fonti disponibili: Binance **{'SI' if row.get('binance_available') else 'NO'}**, Bybit **{'SI' if row.get('bybit_available') else 'NO'}**, KuCoin **{'SI' if row.get('kucoin_available') else 'NO'}**.",
            f"- Consenso multi-exchange: bull {safe_int(row.get('bullish_consensus_count'))}, bear {safe_int(row.get('bearish_consensus_count'))}, divergenze {safe_int(row.get('divergent_metric_count'))}.",
            f"- Flusso taker/order book: **{fmt_score(row.get('flow_score'))}**.",
            f"- OI/funding/basis: **{fmt_score(row.get('derivatives_score'))}**.",
            f"- Affollamento long/short: **{fmt_score(row.get('crowding_score'))}**.",
            f"- Liquidazioni nel campione: **{safe_int(row.get('liquidation_events_sample'))} eventi**, long {fmt_usd(row.get('long_liquidation_usd_sample'))}, short {fmt_usd(row.get('short_liquidation_usd_sample'))}.",
            f"- **Wyckoff:** {row.get('wyckoff_confirmation')}",
            f"- **Fibonacci:** {row.get('fibonacci_confirmation')}",
            f"- **RSI:** {row.get('rsi_confirmation')}",
            f"- **Pattern:** {row.get('pattern_confirmation')}",
            f"- **Breakout/breakdown:** {row.get('breakout_quality')}",
            f"- **Mappa liquidità attuale:** {row.get('liquidity_map')}",
            "",
        ]
        if asset in chart_names:
            lines += [f"![Microstruttura exchange {asset}]({chart_names[asset]})", ""]

    lines += [
        "## Overlay sulle previsioni a 30 giorni",
        "",
        "La previsione storica grezza dello scanner resta intatta. L'overlay exchange può correggerla solo dopo almeno 30 controlli maturati a 30 giorni e solo se il modulo dimostra accuratezza direzionale almeno del 55%.",
        "",
    ]
    overlay_rows: list[list[str]] = []
    for asset in ASSETS:
        row = overlay_map[asset]
        overlay_rows.append(
            [
                asset,
                fmt_pct(row.get("raw_positive_rate_30d")),
                fmt_pct(row.get("raw_return_p50_30d")),
                str(safe_int(row.get("tracker_controls_30d"))),
                fmt_pct(row.get("tracker_accuracy_30d")),
                row.get("overlay_status", ""),
                f"{(safe_float(row.get('overlay_weight'), 0.0) or 0.0):.2f}".replace(".", ","),
                fmt_pct(row.get("adjusted_positive_rate_30d")),
                fmt_pct(row.get("adjusted_return_p50_30d")),
            ]
        )
    lines += [
        md_table(
            [
                "Asset",
                "Prob. grezza salita",
                "Return p50 grezzo",
                "Controlli 30g",
                "Accuratezza exchange",
                "Stato overlay",
                "Peso",
                "Prob. corretta",
                "Return corretto",
            ],
            overlay_rows,
        ),
        "",
        "## Dati salvati",
        "",
        "- `exchange_market_data_snapshot.json`: fotografia raw/derivata Binance + Bybit + KuCoin.",
        "- `exchange_market_data_intraday.csv`: memoria operativa mobile degli ultimi 180 giorni, ripristinata da due copie ridondanti su GitHub Releases.",
        "- `exchange_intraday_YYYY-MM.csv.gz`: archivio mensile permanente dei dati intraday, creato dopo la chiusura del mese.",
        "- `exchange_microstructure_metrics.csv`: score e conferme correnti lette dal Global.",
        "- `exchange_microstructure_history.csv`: prima fotografia giornaliera congelata, usata per valutare le previsioni.",
        "- `exchange_signal_tracker_metrics.csv`: accuratezza a 1/3/7/14/30 giorni.",
        "- `exchange_prediction_overlay.csv`: confronto scanner grezzo vs overlay calibrato.",
        "",
        "## Regole di prudenza",
        "",
        "- Un muro dell'order book può essere cancellato: non è un supporto garantito.",
        "- Funding e long/short ratio misurano affollamento, non direzione certa.",
        "- OI in aumento conta soltanto insieme alla direzione del prezzo e al taker flow.",
        "- Le liquidazioni del campione breve sono diagnostiche e hanno peso ridotto.",
        "- Prima dei 30 controlli a 7g il modulo non pesa nel Global; prima dei 30 controlli a 30g l'overlay non altera le previsioni.",
        "",
        f"Salute fonti: **{safe_text(health.get('status'), 'n/a')}** — coppie exchange/asset disponibili: {safe_int(health.get('available_exchange_asset_pairs'))}/{safe_int(health.get('total_exchange_asset_pairs'))}. "
        f"Binance {status_label(exchange_health_status(health, 'BTC', 'binance'))}; Bybit {status_label(exchange_health_status(health, 'BTC', 'bybit'))}; KuCoin {status_label(exchange_health_status(health, 'BTC', 'kucoin'))}.",
        f"Storage persistente: **{safe_text(storage.get('status'), 'n/a')}** — ultimo asset: {safe_text(storage.get('asset'), 'n/a')}.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def inject(report: str) -> None:
    if not LATEST_REPORT.exists():
        atomic_text(LATEST_REPORT, f"{START_MARKER}\n{report.rstrip()}\n{END_MARKER}\n")
        return
    old = LATEST_REPORT.read_text(encoding="utf-8")
    block = f"{START_MARKER}\n{report.rstrip()}\n{END_MARKER}"
    if START_MARKER in old and END_MARKER in old:
        pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
        new = pattern.sub(block, old, count=1)
    else:
        anchor = "<!-- EXCHANGE_SIGNAL_TRACKER_START -->"
        if anchor in old:
            new = old.replace(anchor, block + "\n\n" + anchor, 1)
        else:
            anchor = "<!-- LIQUIDATION_SUMMARY_START -->"
            if anchor in old:
                new = old.replace(anchor, block + "\n\n" + anchor, 1)
            else:
                anchor = "<!-- TECHNICAL_STRUCTURE_START -->"
                new = old.replace(anchor, block + "\n\n" + anchor, 1) if anchor in old else old.rstrip() + "\n\n" + block + "\n"
    atomic_text(LATEST_REPORT, new)


def main() -> None:
    snapshot = read_json(SNAPSHOT_PATH)
    assets_payload = snapshot.get("assets", {}) if isinstance(snapshot, dict) else {}
    if not isinstance(assets_payload, dict) or not assets_payload:
        raise SystemExit(f"Snapshot exchange mancante o vuoto: {SNAPSHOT_PATH}")

    health = read_json(HEALTH_PATH)
    storage = read_json(STORAGE_STATUS_PATH)
    tech = technical_rows()
    scanner = scanner_rows()
    tracker = tracker_30d_rows()
    tracker_7d = tracker_7d_rows()
    intraday = intraday_summaries()

    metrics: list[dict[str, Any]] = []
    for asset in ASSETS:
        asset_row = assets_payload.get(asset, {})
        if not isinstance(asset_row, dict):
            asset_row = {}
        asset_row = enrich_asset_with_intraday(asset_row, intraday.get(asset, {}))
        metric = score_asset(asset, asset_row, tech.get(asset, {}), tracker_7d.get(asset, {}))
        metric["source_health"] = safe_text(health.get("status"), "n/a")
        for exchange in ("binance", "bybit", "kucoin"):
            metric[f"{exchange}_status"] = exchange_health_status(health, asset, exchange)
        metrics.append(metric)

    overlays = [
        prediction_overlay(asset, next(row for row in metrics if row["asset"] == asset), scanner.get(asset, {}), tracker.get(asset, {}))
        for asset in ASSETS
    ]

    write_csv(METRICS_PATH, metrics, METRIC_FIELDS)
    write_csv(PREDICTION_PATH, overlays, PREDICTION_FIELDS)
    history = update_history(metrics, overlays)
    charts = make_history_charts(history)
    report = render_report(
        metrics,
        overlays,
        health,
        charts,
        safe_int(snapshot.get("liquidation_sample_seconds"), 0),
        storage,
    )
    atomic_text(REPORT_PATH, report)
    atomic_text(DIAGNOSTICS_PATH, render_source_diagnostics(health, storage))
    inject(report)

    print(f"Exchange microstructure report scritto in: {REPORT_PATH}")
    print(f"Diagnostica fonti scritta in: {DIAGNOSTICS_PATH}")
    print(f"Metriche exchange scritte in: {METRICS_PATH}")
    print(f"History exchange scritta in: {HISTORY_PATH}")
    print(f"Overlay previsione scritto in: {PREDICTION_PATH}")
    for row in metrics:
        print(
            f"{row['asset']}: raw {fmt_score(row['raw_score'])} | candidato {fmt_int_score(row['candidate_global_score'])} | "
            f"Global {fmt_int_score(row['global_score'])} | {row['bias']} | {row['confidence']}"
        )


if __name__ == "__main__":
    main()
